import React from "react";
import home from "./Home.module.css";
import artificialImg from "../../assets/artificialModel.png";
import { RiInstagramFill, RiFacebookBoxFill } from "react-icons/ri";
import { TiSocialSkype } from "react-icons/ti";

const Home = () => {
  return (
    <div className={home.homeContainer}>
      <div className={home.heroSection}>
        <div className={home.heroText}>
          <h1>AI Detector for ChatGPT, GPT4, Bard & More</h1>
          <p>
            We are pleased to announce that our grading system has been updated
            to incorporate advanced AI detection modeling, utilizing a greater
            amount of gpt-4 and gpt-3.5 content. As a result, our AI checker now
            boasts an impressive level of accuracy, achieving a success rate of
            98.3%. To simplify the scoring process, we have implemented an
            overall probability score, indicating the likelihood of the content
            being written by a human. Our AI technology is derived from ChatGPT,
            GPT4, and Bard, and is widely regarded as one of the most reliable
            and comprehensive AI content detectors available. It is important to
            note that content detected as being generated by AI may have a
            negative impact on search engine rankings, essay grades, and reader
            perception. A score of 1% indicates a 99% probability that the
            content was created by AI.
          </p>
          <a
            href="https://platform.openai.com/docs/introduction"
            target="_blank"
            className={home.learnmore}
          >
            Learn more
          </a>
        </div>
        <div className={home.heroImg}>
          <img src={artificialImg} alt="" width={"100%"} height={"100%"} />
        </div>
      </div>
      <div></div>
      <div className={home.footer}>
        <div className={home.socialMedia}>
          <div>
            <h3>Let's Talk GPT</h3>
            <p>
              Discuss with ChatGPT on WhatsApp & TeleGram. Premium and Reliable
              Chat GPT whatsApp & Chat GPT TeleGram tool
            </p>
            <a href="https://www.letstalkgpt.com/?r=zgproducts">Learn more</a>
          </div>
          <div>
            <h3>SendBig</h3>
            <p>
              Quickly and Securely deliver large files—up to 30 GB for Free—to
              anyone. Unique features, detailed dashboard, ISO Certified service
              and a fully customizable experience
            </p>
            <a href="https://www.sendbig.com/?r=zgproducts">Learn more</a>
          </div>
          <div>
            <h3>Unreal Person</h3>
            <p>
              The most advanced AI image generator for Human,Cat,Horse and
              Art.With UnrealPerson generate Fake images with AI that looks 100%
              real but they don't exist in reality!
            </p>
            <a href="https://www.unrealperson.com/?r=zgproducts">Learn more</a>
          </div>
          <div>
            <h3>Pomonow</h3>
            <p>
              The famous Time Management method that Boosts your Productivity
              while working or studying, It is PomoNow, one of the popular time
              management hacks used today.
            </p>
            <a href="https://www.pomonow.com/?r=zgproducts">Learn more</a>
          </div>
        </div>

        <div className={home.footerSection}>
          <div className={home.footerMedia}>
            <p>About</p>
            <span className={home.abouttext}>
              Chat GPT is an artificial intelligence program that generates
              dialogue. Created by Open ai of data to generate responses to user inquiries.
            </span>
          </div>
          <div className={home.footerLink}>
            <p style={{ fontSize: "20px" }}>Links</p>
            <p> <a href="https://platform.openai.com/docs" >documention</a></p>
            <p> <a href="/login">login</a></p>
            <p> <a href="/signup">signup</a></p>
            <p> <a href="https://platform.openai.com/examples">support</a></p>
          </div>
          <div className={home.socialMediaIcon}>
            <p style={{ textAlign: "center" }}>Social media</p>
            <p
              style={{
                fontSize: "16px",
                textAlign: "center",
                padding: "10px 0px",
              }}
            >
              Follow in social media
            </p>

            <section className={home.socialIcon}>
              <RiFacebookBoxFill color="#f0ecec6c" size={40} />
              <RiInstagramFill color="#f0ecec6c" size={40} />
              <TiSocialSkype color="#f0ecec6c" size={40} />
            </section>
          </div>
        </div>

        <div className={home.copyRight}>
          <p>&copy;Copyright 2023 All rights reserved by chat gpt.</p>
          <p>Educational purpose</p>
        </div>
      </div>
    </div>
  );
};

export default Home;
